source 'http://rubygems.org'

ruby '2.1.0'

gem 'rails', '4.1.6'

gem 'inherited_resources'
gem 'pg'
gem 'slim'
gem 'slim-rails'
gem 'devise'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'rails-i18n', github: 'svenfuchs/rails-i18n', branch: 'master'
gem 'neat'
gem 'normalize-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'underscore-rails'
gem 'fb-channel-file'
gem 'spring', group: :development
gem 'rails_12factor', group: :production
gem 'pundit'
gem 'letter_opener', group: :development
gem 'active_decorator'
gem 'rest_in_place'
gem 'autosize-rails'
gem 'jbuilder'
gem 'auto_html', '= 1.5.1'
gem 'RedCloth'
gem 'moip-assinaturas'
gem 'paperclip', '~> 4.1.1'
gem 'paperclip-meta'
gem 'aws-sdk'
gem 'icomoon-rails'
gem 'pickadate-rails'
gem 'brhelper'
gem 'state_machine'
gem 'high_voltage'
